# Base Config Variables
base:
  api: "kaggle"
  base_url: "https://www.kaggle.com/api/v1"
  endpoint: "datasets/download"
  database_source: "mysql"
  

# API Specific Variables
api:
  owner: "shivamb"
  dataset: "netflix-shows"
  version: "5"
   

# Database Specific Variables
database:
  name: ""
  table: ""
  queries: {
    "create": "
      CREATE TABLE IF NOT EXISTS {table} (
        show_id VARCHAR(50) PRIMARY KEY,
        type VARCHAR(50),
        title VARCHAR(255),
        director VARCHAR(255),
        cast TEXT,
        country VARCHAR(100),
        date_added DATE,
        release_year VARCHAR(10),
        rating VARCHAR(10),
        duration VARCHAR(50),
        listed_in TEXT,
        description TEXT,
        adults_only BOOLEAN,
        diversity_score INT
      )
    "
  }
