# Base Config Variables
base:
  api: "kaggle"
  base_url: "https://www.kaggle.com/api/v1"
  endpoint: "datasets/download"
  database_source: "mysql"
  

# API Specific Variables
api:
  owner: "shivamb"
  dataset: "netflix-shows"
  version: "5"
   

# Database Specific Variables
database:
  name: "etl_app_data"
  table: "netflix_shows_data"
  queries: {
    "create": "
      CREATE TABLE IF NOT EXISTS {table} (
        show_id VARCHAR(50) PRIMARY KEY,
        type VARCHAR(50),
        title VARCHAR(255),
        director VARCHAR(255),
        cast TEXT,
        country VARCHAR(225),
        date_added DATE,
        release_year VARCHAR(10),
        rating VARCHAR(10),
        duration VARCHAR(50),
        listed_in TEXT,
        description TEXT,
        diversity_score INT,
        adults_only VARCHAR(50)
      )
    "
  }
  visualisations: {
    "columns": ["release_year", "diversity_score"],
    "title": "Average Media Genre Diversity Over Time",
    "xlabel": "Year",
    "ylabel": "Average Score"
  }
